class Normalizer {
  static normalizeSpecialCharacters(inputString) {
    const specialCharacters = {
      // Correspondances pour la police Arial
      À: "A",
      Á: "A",
      Â: "A",
      Ã: "A",
      Ä: "A",
      Å: "A",
      Æ: "AE",
      Ç: "C",
      È: "E",
      É: "E",
      Ê: "E",
      Ë: "E",
      Ì: "I",
      Í: "I",
      Î: "I",
      Ï: "I",
      Ð: "D",
      Ñ: "N",
      Ò: "O",
      Ó: "O",
      Ô: "O",
      Õ: "O",
      Ö: "O",
      Ø: "O",
      Ù: "U",
      Ú: "U",
      Û: "U",
      Ü: "U",
      Ý: "Y",
      Þ: "TH",
      ß: "ss",
      à: "a",
      á: "a",
      â: "a",
      ã: "a",
      ä: "a",
      å: "a",
      æ: "ae",
      ç: "c",
      è: "e",
      é: "e",
      ê: "e",
      ë: "e",
      ì: "i",
      í: "i",
      î: "i",
      ï: "i",
      ð: "d",
      ñ: "n",
      ò: "o",
      ó: "o",
      ô: "o",
      õ: "o",
      ö: "o",
      ø: "o",
      ù: "u",
      ú: "u",
      û: "u",
      ü: "u",
      ý: "y",
      þ: "th",
      ÿ: "y",
      ẞ: "SS",
      // Correspondances pour la police 𝐀𝐢𝐦𝐋𝐚𝐠
      "𝐀": "A",
      "𝐁": "B",
      "𝐂": "C",
      "𝐃": "D",
      "𝐄": "E",
      "𝐅": "F",
      "𝐆": "G",
      "𝐇": "H",
      "𝐈": "I",
      "𝐉": "J",
      "𝐊": "K",
      "𝐋": "L",
      "𝐌": "M",
      "𝐍": "N",
      "𝐎": "O",
      "𝐏": "P",
      "𝐐": "Q",
      "𝐑": "R",
      "𝐒": "S",
      "𝐓": "T",
      "𝐔": "U",
      "𝐕": "V",
      "𝐖": "W",
      "𝐗": "X",
      "𝐘": "Y",
      "𝐙": "Z",
      "𝐚": "a",
      "𝐛": "b",
      "𝐜": "c",
      "𝐝": "d",
      "𝐞": "e",
      "𝐟": "f",
      "𝐠": "g",
      "𝐡": "h",
      "𝐢": "i",
      "𝐣": "j",
      "𝐤": "k",
      "𝐥": "l",
      "𝐦": "m",
      "𝐧": "n",
      "𝐨": "o",
      "𝐩": "p",
      "𝐪": "q",
      "𝐫": "r",
      "𝐬": "s",
      "𝐭": "t",
      "𝐮": "u",
      "𝐯": "v",
      "𝐰": "w",
      "𝐱": "x",
      "𝐲": "y",
      "𝐳": "z",
      // Correspondances pour la police 𝑉𝑎𝑙𝑜
      "𝑨": "A",
      "𝑩": "B",
      "𝑪": "C",
      "𝑫": "D",
      "𝑬": "E",
      "𝑭": "F",
      "𝑮": "G",
      "𝑯": "H",
      "𝑰": "I",
      "𝑱": "J",
      "𝑲": "K",
      "𝑳": "L",
      "𝑴": "M",
      "𝑵": "N",
      "𝑶": "O",
      "𝑷": "P",
      "𝑸": "Q",
      "𝑹": "R",
      "𝑺": "S",
      "𝑻": "T",
      "𝑼": "U",
      "𝑽": "V",
      "𝑾": "W",
      "𝑿": "X",
      "𝒀": "Y",
      "𝒁": "Z",
      "𝒂": "a",
      "𝒃": "b",
      "𝒄": "c",
      "𝒅": "d",
      "𝒆": "e",
      "𝒇": "f",
      "𝒈": "g",
      "𝒉": "h",
      "𝒊": "i",
      "𝒋": "j",
      "𝒌": "k",
      "𝒍": "l",
      "𝒎": "m",
      "𝒏": "n",
      "𝒐": "o",
      "𝒑": "p",
      "𝒒": "q",
      "𝒓": "r",
      "𝒔": "s",
      "𝒕": "t",
      "𝒖": "u",
      "𝒗": "v",
      "𝒘": "w",
      "𝒙": "x",
      "𝒚": "y",
      "𝒛": "z",
      // Correspondances pour la police Ｇｅｓｔｉｏｎ
      Ａ: "A",
      Ｂ: "B",
      Ｃ: "C",
      Ｄ: "D",
      Ｅ: "E",
      Ｆ: "F",
      Ｇ: "G",
      Ｈ: "H",
      Ｉ: "I",
      Ｊ: "J",
      Ｋ: "K",
      Ｌ: "L",
      Ｍ: "M",
      Ｎ: "N",
      Ｏ: "O",
      Ｐ: "P",
      Ｑ: "Q",
      Ｒ: "R",
      Ｓ: "S",
      Ｔ: "T",
      Ｕ: "U",
      Ｖ: "V",
      Ｗ: "W",
      Ｘ: "X",
      Ｙ: "Y",
      Ｚ: "Z",
      ａ: "a",
      ｂ: "b",
      ｃ: "c",
      ｄ: "d",
      ｅ: "e",
      ｆ: "f",
      ｇ: "g",
      ｈ: "h",
      ｉ: "i",
      ｊ: "j",
      ｋ: "k",
      ｌ: "l",
      ｍ: "m",
      ｎ: "n",
      ｏ: "o",
      ｐ: "p",
      ｑ: "q",
      ｒ: "r",
      ｓ: "s",
      ｔ: "t",
      ｕ: "u",
      ｖ: "v",
      ｗ: "w",
      ｘ: "x",
      ｙ: "y",
      ｚ: "z",
    };

    // Utilisation de l'expression régulière pour rechercher et remplacer les caractères spéciaux
    return inputString.replace(/[\u{1D400}-\u{1D7FF}]/gu, (character) => {
      return specialCharacters[character] || character;
    });
  }
}

class UnNormalizer {
  static useChannelSpecialCharacters(inputString) {
    const specialCharacters = {
      A: "𝑨",
      B: "𝑩",
      C: "𝑪",
      D: "𝑫",
      E: "𝑬",
      F: "𝑭",
      G: "𝑮",
      H: "𝑯",
      I: "𝑰",
      J: "𝑱",
      K: "𝑲",
      L: "𝑳",
      M: "𝑴",
      N: "𝑵",
      O: "𝑶",
      P: "𝑷",
      Q: "𝑸",
      R: "𝑹",
      S: "𝑺",
      T: "𝑻",
      U: "𝑼",
      V: "𝑽",
      W: "𝑾",
      X: "𝑿",
      Y: "𝒀",
      Z: "𝒁",
      a: "𝒂",
      b: "𝒃",
      c: "𝒄",
      d: "𝒅",
      e: "𝒆",
      f: "𝒇",
      g: "𝒈",
      h: "𝒉",
      i: "𝒊",
      j: "𝒋",
      k: "𝒌",
      l: "𝒍",
      m: "𝒎",
      n: "𝒏",
      o: "𝒐",
      p: "𝒑",
      q: "𝒒",
      r: "𝒓",
      s: "𝒔",
      t: "𝒕",
      u: "𝒖",
      v: "𝒗",
      w: "𝒘",
      x: "𝒙",
      y: "𝒚",
      z: "𝒛",
    };

    // Utilisation de l'expression régulière pour rechercher et remplacer les caractères spéciaux
    return inputString.replace((character) => {
      return specialCharacters[character] || character;
    });
  }
}

module.exports = { Normalizer: Normalizer, UnNormalizer: UnNormalizer };
